logger:
  default: info
  logs:
    custom_components.modbus_manager: debug
    custom_components.modbus_manager.sensor: debug
    custom_components.modbus_manager.__init__: debug
    homeassistant.components.modbus: debug
    pymodbus: debug
    asyncio: debug 