reload:
  name: Reload
  description: Reload all Modbus Manager configurations without restart.

sync_device_time:
  name: Sync Device Time
  description: Synchronize device time with Home Assistant time.
  target:
    entity:
      integration: modbus_manager
      domain: sensor

batch_read:
  name: Batch Read
  description: Read multiple registers in one operation.
  fields:
    device_id:
      name: Device ID
      description: The ID of the device to read from
      required: true
      selector:
        text:
    register_type:
      name: Register Type
      description: Type of registers to read
      required: true
      selector:
        select:
          options:
            - "holding"
            - "input"
    start_address:
      name: Start Address
      description: Starting register address
      required: true
      selector:
        number:
          min: 0
          max: 65535
    count:
      name: Count
      description: Number of registers to read
      required: true
      selector:
        number:
          min: 1
          max: 125 

test_device_type:
  name: Test Device Type
  description: Test loading a specific device type
  fields:
    device_type:
      name: Device Type
      description: The device type to test
      required: true
      example: "sungrow_shrt" 