# Modbus Manager Services
# Services for controlling devices

set_ev_charger_current:
  name: "Set EV Charger Current"
  description: "Set the maximum current for all phases of an EV charger"
  fields:
    entity_id:
      name: "Entity ID"
      description: "The EV charger entity ID"
      required: true
      selector:
        entity:
          domain: sensor
          device_class: current
    current:
      name: "Current"
      description: "Maximum current in Amperes (0-16)"
      required: true
      selector:
        number:
          min: 0
          max: 16
          step: 1
          unit_of_measurement: "A"
    phases:
      name: "Phases"
      description: "Number of phases to set (1, 2, or 3)"
      required: false
      default: 3
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"

set_ev_charger_fallback_current:
  name: "Set EV Charger Fallback Current"
  description: "Set the fallback current for all phases of an EV charger"
  fields:
    entity_id:
      name: "Entity ID"
      description: "The EV charger entity ID"
      required: true
      selector:
        entity:
          domain: sensor
          device_class: current
    current:
      name: "Fallback Current"
      description: "Fallback current in Amperes (0-16)"
      required: true
      selector:
        number:
          min: 0
          max: 16
          step: 1
          unit_of_measurement: "A"
    phases:
      name: "Phases"
      description: "Number of phases to set (1, 2, or 3)"
      required: false
      default: 3
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"

modbus_manager_optimize_registers:
  name: "Optimize Modbus Registers"
  description: "Optimize register reading for a specific device"
  fields:
    device_id:
      name: "Device ID"
      description: "The device ID to optimize registers for"
      required: true
      example: "modbus_manager_SG2"

modbus_manager_get_performance:
  name: "Get Performance Metrics"
  description: "Get performance metrics for a device or globally"
  fields:
    device_id:
      name: "Device ID"
      description: "The device ID to get metrics for (optional for global metrics)"
      required: false
      example: "modbus_manager_SG2"

modbus_manager_reset_performance:
  name: "Reset Performance Metrics"
  description: "Reset performance metrics for a device or globally"
  fields:
    device_id:
      name: "Device ID"
      description: "The device ID to reset metrics for (optional for global reset)"
      required: false
      example: "modbus_manager_SG2"
