device_config:
  firmware_handling:
    auto_detect: true
    version_register: 5000  # Register für Firmware-Version
    version_type: "string"  # oder "uint16" etc.
    update_on_version_change: true
    fallback_version: "1.0.0" 