# Sungrow SH-RT Hybrid Wechselrichter (3-Phasen mit Batterie)
# Basierend auf https://github.com/mkaiser/Sungrow-SHx-Inverter-Modbus-Home-Assistant

device_info:
  name: "Test Device"
  manufacturer: "ModbusManager"
  model: "Test"
  description: "Testger채t f체r die Entwicklung"

# Firmware-Konfiguration
firmware:
  version_registers:
    - name: "arm_software_version_1"
      address: 4953
    - name: "arm_software_version_2"
      address: 4954
  version_type: "uint16"
  version_format: "{:d}.{:d}.{:d}.{:d}"  # Format: Major.Minor.Build.Revision
  auto_detect: true
  fallback_version: "1.0.0"

# Modbus-Konfiguration
modbus:
  slave_id: 1
  connection:
    timeout: 3
    retry_delay: 0.1
    max_retries: 3
    batch_size: 100

# Polling-Konfiguration
polling:
  fast:
    interval: 5
    registers: [
      "arm_software_version",
      "dsp_software_version",
      "inverter_start_stop"
    ]
  normal:
    interval: 30
    registers: ["running_state"]
  slow:
    interval: 600
    registers: []

firmware_versions:
  "1.0.0":  # Original Firmware
    registers:
      read:
        - { name: "running_state", address: 13000, type: "uint16", state_class: "measurement", translation_key: "sensor.running.state", scale: 1, precision: 0 }
        # ... weitere Register

  "1.0.23":  # Neue Firmware mit ge채nderten Registern
    registers:
      read:
        - { name: "battery_power", address: 13025, type: "int32" }
        # ... ge채nderte Register       
         
# Register-Definitionen
registers:
  read:
    # ARM Software Version (4953-4967)
    # Die Version wird aus mehreren Registern zusammengesetzt
    # Beispiel: Register 4953 = 0x0123, 4954 = 0x0456 ergibt Version 1.23.4.56
    - name: "arm_software_version_1"
      address: 4953
      type: "uint16"
      description: "ARM Software Version Major/Minor (0xAABB = Version AA.BB)"
      debug: true
    - name: "arm_software_version_2"
      address: 4954
      type: "uint16"
      description: "ARM Software Version Build/Revision (0xCCDD = Version CC.DD)"
      debug: true
    - name: "arm_software_version_3"
      address: 4955
      type: "uint16"
      description: "ARM Software Version Additional Info 1"
      debug: true
    - name: "arm_software_version_4"
      address: 4956
      type: "uint16"
      description: "ARM Software Version Additional Info 2"
      debug: true

    # DSP Software Version (4968-4982)
    # Die Version wird aus mehreren Registern zusammengesetzt
    # Beispiel: Register 4968 = 0x0123, 4969 = 0x0456 ergibt Version 1.23.4.56
    - name: "dsp_software_version_1"
      address: 4968
      type: "uint16"
      description: "DSP Software Version Major/Minor (0xAABB = Version AA.BB)"
      debug: true
    - name: "dsp_software_version_2"
      address: 4969
      type: "uint16"
      description: "DSP Software Version Build/Revision (0xCCDD = Version CC.DD)"
      debug: true
    - name: "dsp_software_version_3"
      address: 4970
      type: "uint16"
      description: "DSP Software Version Additional Info 1"
      debug: true
    - name: "dsp_software_version_4"
      address: 4971
      type: "uint16"
      description: "DSP Software Version Additional Info 2"
      debug: true

  write:
    # holding registers
    - name: "inverter_start_stop"
      address: 12999
      type: "uint16"