# Development helpers for Modbus Manager
input_button:
  reload_modbus_manager:
    name: Reload Modbus Manager
    icon: mdi:reload

automation:
  - alias: "Reload Modbus Manager Integration"
    trigger:
      platform: event
      event_type: call_service
      event_data:
        domain: input_button
        service: press
        service_data:
          entity_id: input_button.reload_modbus_manager
    action:
      - service: homeassistant.reload_config_entry
        target:
          entity_id: "*modbus_manager*" 